spring:
  datasource:
    url: jdbc:mysql://${mysql.host}/vacinas?createDatabaseIfNotExist=true
    username: ${mysql.username}
    password: ${mysql.password}
  profiles:
    active: dev
  liquibase:
    enabled: false
    change-log: liquibase/master.yaml
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
