on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  execute_unit_tests:
    name: Execute unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Dizer olá
        run: echo EEEPAAA!